### ISSUE TITLE
Mac os xcode-select error

### ISSUE THREAD

**Issue by den-vasyliev** [vidovgopol/kbot#1]
Could you please take a look at the error on my Mac?

`➜  kbot git:(develop) ✗ git commit -am 'a'                                                                                   
xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
➜  kbot git:(develop) ✗ uname -a
Darwin Mac-mini 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101 arm64`

**Comment by vidovgopol** [comment]
Hello Denis,
I want to ask, did this problem appear after gitleaks install? Or it is allso present when you use git utility without gitleaks?

I have found some workaround to fix this:

[https://apple.stackexchange.com/questions/161648/how-to-use-gcc-or-git-without-installing-xcode](url)

Also my script has been tested on Mac-mini, and everything was worked as expected:

```
@Mac-mini-admin kbot % uname -a
Darwin Mac-mini-admin.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64
```

**Comment by den-vasyliev** [comment]
Thanks for the reply!
No gitleaks installed
Please find full log to reproduce:

`➜  prom git clone https://github.com/maksym-alekseiev/kbot
 
Cloning into 'kbot'...
remote: Enumerating objects: 98, done.
remote: Counting objects: 100% (98/98), done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 98 (delta 50), reused 74 (delta 26), pack-reused 0
Receiving objects: 100% (98/98), 42.65 KiB | 3.55 MiB/s, done.
Resolving deltas: 100% (50/50), done.

➜  prom cd kbot 

➜  kbot git:(main) curl -sSL  https://raw.githubusercontent.com/vidovgopol/kbot/master/scripts/gitleaks_install.sh  | sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2273  100  2273    0     0  43061      0 --:--:-- --:--:-- --:--:-- 54119

➜  kbot git:(main) ✗ git config hooks.gitleaks enable   
                
➜  kbot git:(main) ✗ git commit -am 'test'

xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.`

**Comment by vidovgopol** [comment]
One of students Oleksandr Schweizer has helped me to test script on his mac.
And the script worked fine from the first try.
I suppose that this issue is connected to your mac env and this has to be fixed manually.

Also I tried to reproduce issue with command that you send:

admin@Mac-mini-admin kbot2 % **git clone https://github.com/maksym-alekseiev/kbot**
admin@Mac-mini-admin kbot2 % **cd kbot**
admin@Mac-mini-admin kbot % **curl -sSL https://raw.githubusercontent.com/vidovgopol/kbot/master/scripts/gitleaks_install.sh | sh**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2273  100  2273    0     0   4685      0 --:--:-- --:--:-- --:--:--  4775
admin@Mac-mini-admin kbot %  **git config hooks.gitleaks enable**
admin@Mac-mini-admin kbot % **git commit -am 'test'**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2708k  100 2708k    0     0  1262k      0  0:00:02  0:00:02 --:--:-- 1965k

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

11:46AM INF 0 commits scanned.
11:46AM INF scan completed in 67.6ms
11:46AM INF no leaks found

**Comment by den-vasyliev** [comment]
> One of students Oleksandr Schweizer has helped me to test script on his mac. And the script worked fine from the first try. I suppose that this issue is connected to your mac env and this has to be fixed manually.
> 
> Also I tried to reproduce issue with command that you send:
> 
> admin@Mac-mini-admin kbot2 % **git clone https://github.com/maksym-alekseiev/kbot** admin@Mac-mini-admin kbot2 % **cd kbot** admin@Mac-mini-admin kbot % **curl -sSL https://raw.githubusercontent.com/vidovgopol/kbot/master/scripts/gitleaks_install.sh | sh** % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 100 2273 100 2273 0 0 4685 0 --:--:-- --:--:-- --:--:-- 4775 admin@Mac-mini-admin kbot % **git config hooks.gitleaks enable** admin@Mac-mini-admin kbot % **git commit -am 'test'** % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 2708k 100 2708k 0 0 1262k 0 0:00:02 0:00:02 --:--:-- 1965k
> 
> ```
> ○
> │╲
> │ ○
> ○ ░
> ░    gitleaks
> ```
> 
> 11:46AM INF 0 commits scanned. 11:46AM INF scan completed in 67.6ms 11:46AM INF no leaks found

Thanks for testing. Correct - you got it worked due the x-code installed on customer mac. Do i need x-code (aprox 20G) to run your script? All other pre-commits works perfectly on my side. 

So the question is - what exectly triggered x-code dependency for mac users?

**Comment by vidovgopol** [comment]
I have made some investigation about this problem and found that,
this problem about shebang value in script.
Without xcode installed on Mac, default path to python3 is:  #!/usr/local/bin/python3

But in my script I use: #!/usr/bin/python3 this path is unavailable without x-code, and script falls.

For solution, we can change shebang value if you don't want to install xcode.
Also, I found that it is possible to install xcode command line utilities with size only 130Mb.

[https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a](url)

I have never ever worked on Mac that's why I missed this aspect, with developer tools is macOS.

Also, probably you can propose more appropriate solution to fix this up)

**Comment by den-vasyliev** [comment]
this solves my mac issue - thanks!
